name: Latests Blog Posts I've done
on:
    schedule:
        - cron: 0 0 */2 * *
    workflow_dispatch:

jobs:
    update-readme-with-blog:
        name: Updates README latest feed of posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                feed_list: "https://dev.to/feed/nomade55"


